### ISSUE TITLE
Image height - Change to auto to make it responsive

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/fresnovdp#3]
@geekwise-kao-thao 

`height:auto;` for images to scale responsively
the width should be set to `width:calc(100%/6);` for some of those logos.
The image tag is an inline item and not a block.
You will not be able to set it to center without `display:block;`

**Comment by geekwise-kao-thao** [comment]
can you check it now?  i'll work on media query for different sizes
